#!/usr/bin/env python3
# Created by: Katie G
# Created on: October 11th, 2022
# This program makes the user guess
# a random number generated by the
# program, then checks to see if that number
# is the same as the one the program
# generated. The program then displays
# the result back to the user.
import random


# this function gets the user's guess,
# generates a random number, then checks
# to see if it is equal to the user's num.
# The function then displays the result
# to the user.
def main():
    # getting the guess from the user
    user_guess = int(
        input(
            "My little friend has generated a random number between 0-9. "
            "Guess what it is :) "
            )
        )

    # the program generates a random number from 0-9.
    generated_num = random.randint(0, 9)

    # checks to see if user guess is equal to generated num.
    # if so, prints "you got it right". else, prints
    # "you did not get it right".
    if user_guess == generated_num:
        print("You got it right! Well done :)")
    else:
        print("You did not get it right. :(")


if __name__ == "__main__":
    main()
